name: Publish Container image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - id: ghcr_login
        uses: docker/login-action@v1
        with:
            registry: ghcr.io
            username: ${{ secrets.DEREK_GHCR_UNAME }}
            password: ${{ secrets.DEREK_GHCR_PAT }}

      - name: Check out the repo
        uses: actions/checkout@v2
      
      - id: tag_prep
        run:
          echo ::set-output name=short-ref::$(echo ${{ github.ref }} | sed -e 's/refs\/tag\///g')

      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/grype-scan-rep:ubuntu-latest
            ghcr.io/${{ github.repository }}/grype-scan-rep:${{ steps.tag_prep.outputs.short-ref }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.title=Grype-Scan-Repo